version: 2.1

jobs:
  deploy_staging:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip  # Or your desired version
            unzip terraform_1.5.0_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
      - run:
          name: Terraform Init (Staging)
          command: |
            cd environments/staging
            terraform init
      - run:
          name: Terraform Plan (Staging)
          command: |
            cd environments/staging
            terraform plan
      - run:
          name: Terraform Apply (Staging)
          command: |
            cd environments/staging
            terraform apply -auto-approve
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/gcp-credentials.json # Path to your service account key
      - persist_to_workspace:
          root: .
          paths:
            - environments/staging/.terraform* # Persist Terraform state

  deploy_production:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip  # Or your desired version
            unzip terraform_1.5.0_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
      - run:
          name: Terraform Init (Production)
          command: |
            cd environments/production
            terraform init
      - run:
          name: Terraform Plan (Production)
          command: |
            cd environments/production
            terraform plan
      - run:
          name: Terraform Apply (Production)
          command: |
            cd environments/production
            terraform apply -auto-approve
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/gcp-credentials.json # Path to your service account key
      - persist_to_workspace:
          root: .
          paths:
            - environments/production/.terraform* # Persist Terraform state

workflows:
  terraform_deploy:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only:
                - staging
      - deploy_production:
          filters:
            branches:
              only:
                - master
