version: 2.1

commands:
  terraform_init_plan_apply:
    description: "Plan Terraform deployment"
    parameters:
      env:
        type: string
    steps:
      - run:
          name: Terraform Plan
          command: |
            cd terraform/environments/<< parameters.env >>
            terraform init -input=false
            terraform plan -out tfapply
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /root/.gcp/credentials.json
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform_apply:
    description: "Apply Terraform deployment"
    parameters:
      env:
        type: string
    steps:
      - run:
          name: Terraform Apply
          command: |
            cd terraform/environments/<< parameters.env >>
            terraform apply -auto-approve tfapply
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /root/.gcp/credentials.json
      - run:
          name: Retrieve Instance ID
          command: |
            INSTANCE_ID=$(terraform output -raw instance_id)
            echo "The instance ID is: $INSTANCE_ID"

  terraform_plan_destroy:
    description: "Plan Terraform destroy"
    parameters:
      env:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Create Destroy Plan
          command: |
            cd terraform/environments/<< parameters.env >>
            terraform plan -destroy -out tfdestroy
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /root/.gcp/credentials.json
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform_destroy:
    description: "Destroy Terraform deployment"
    parameters:
      env:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Destroy
          command: |
            cd terraform/environments/<< parameters.env >>
            terraform apply -auto-approve tfdestroy
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /root/.gcp/credentials.json

jobs:
  deploy_staging:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Setup GCP Credentials
          command: |
            mkdir -p /root/.gcp
            echo $GOOGLE_APPLICATION_CREDENTIALS > /root/.gcp/credentials.json
      - terraform_init_plan_apply:
          env: staging
      - terraform_apply:
          env: staging
      - terraform_plan_destroy:
          env: staging
      - terraform_destroy:
          env: staging
      - persist_to_workspace:
          root: .
          paths:
            - terraform/environments/staging/.terraform* # Persist Terraform state

  deploy_production:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Setup GCP Credentials
          command: |
            mkdir -p /root/.gcp
            echo $GOOGLE_APPLICATION_CREDENTIALS > /root/.gcp/credentials.json
      - terraform_init_plan_apply:
          env: production
      - terraform_apply:
          env: production
      - terraform_plan_destroy:
          env: production
      - terraform_destroy:
          env: production
      - persist_to_workspace:
          root: .
          paths:
            - terraform/environments/production/.terraform* # Persist Terraform state

workflows:
  terraform_deploy:
    jobs:
      - deploy_staging:
          filters:
            branches:
              only:
                - staging
      - deploy_production:
          filters:
            branches:
              only:
                - master
